version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

executors:
  py-executor:
    # working_directory: /tmp
    docker:
      - image: circleci/python:3.7.3
  py-builder:
    machine:
      enabled: true
      image: circleci/classic:201808-01
      docker_layer_caching: true

jobs:
  lint_and_test:
    executor:
      name: py-executor
    steps:
      - checkout
      - run:
          name: Print info
          when: always
          command: |
            ls -lRt && pwd && uname -a && git tag --list && python -V && pip -V && id
      - run:
          name: Init enviroment
          when: always
          command: |
            sudo pip install -U pip
            sudo pip install -r requirements.txt
      - run:
          name: Run black
          when: always
          command: |
            find . -type f -name "*.py" | grep -v "py-dep-kun" | xargs -L 1 black --check && echo 0
            find . -type f -name "*.py" | grep -v "py-dep-kun" | xargs -L 1 black --diff && echo 0
            find . -type f -name "*.py" | grep -v "py-dep-kun" | xargs -L 1 black ; echo $?
      - run:
          name: Run formerly
          when: always
          command: |
            find . -type f -name "*.py" | grep -v "py-dep-kun" | xargs -L 1 pycodestyle ; echo $? && echo 0
      - run:
          name: Run type check
          when: always
          command: |
            mypy -V
            mypy -v --no-warn-no-return run.py
      - run:
          name: Run tests
          when: always
          command: |
            pytest --version
            pytest -v --show-capture=no --cache-clear --setup-show
            pytest -v --show-capture=no --cache-clear --setup-show --randomly-seed=last
      - run:
          name: Output coverage report
          when: always
          command: |
            pytest --cov .
            pytest --cov . --cov-report html
      - store_test_results:
          path: htmlcov
      - store_artifacts:
          path: htmlcov
      - run:
          name: Upload covrage
          when: always
          command: |
            codecov

  build_and_deploy:
    executor:
      name: py-builder
    steps:
      - checkout
      - run:
          name: Print info
          when: always
          command: |
            docker version && docker-compose version
      - run:
          name: Build container
          when: always
          command: |
            docker image build -t py-dep-kun .
            docker image ls
      - run:
          name: Add container tag
          when: always
          command: |
            docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASS}
            docker tag py-dep-kun ${DOCKERHUB_USER}/${DOCKERHUB_REPOS}:${CIRCLE_TAG}
            docker image ls
            docker image push ${DOCKERHUB_USER}/${DOCKERHUB_REPOS}:${CIRCLE_TAG}

workflows:
  version: 2
  defaultWorkflow:
    jobs:
      - lint_and_test:
          filters:
            branches:
              only:
                - master
                - beta
                - alpha
            tags:
              only: /v.*/
      # Flow to be executed only when pushing with tag
      - build_and_deploy:
          requires:
            - lint_and_test
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/
