version: 2.1

executors:
  py-executor:
    # working_directory: /tmp
    docker:
      - image: circleci/python:3.7.3

jobs:
  lint_and_test:
    executor:
      name: py-executor
    steps:
      - checkout
      - run:
          name: Print info
          when: always
          command: |
            ls -lRt && pwd && uname -a && git tag --list && python -V && pip -V && id
      - run:
          name: Init enviroment
          when: always
          command: |
            sudo pip install -U pip
            sudo pip install -r requirements.txt
      - run:
          name: Run black
          when: always
          command: |
            find . -type f -name "*.py" | grep -v "py-dep-kun" | xargs -L 1 black --check
            find . -type f -name "*.py" | grep -v "py-dep-kun" | xargs -L 1 black --diff
            find . -type f -name "*.py" | grep -v "py-dep-kun" | xargs -L 1 black ; echo $?
      - run:
          name: Run formerly
          when: always
          command: |
            find . -type f -name "*.py" | grep -v "py-dep-kun" | xargs -L 1 pycodestyle ; echo $?
      - run:
          name: Run type check
          when: always
          command: |
            mypy -V
            mypy run.py
      - run:
          name: Run tests
          when: always
          command: |
            pytest --version
            pytest -v

workflows:
  version: 2
  # Execute all branch flows
  build_and_test:
    jobs:
      - lint_and_test
  # Flow to be executed only when pushing with tag
  tagged-build:
    jobs:
      - lint_and_test:
          filters:
            tags:
              only: /^v.*/
